spring.application.name=illuminactivity

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:~/${spring.application.name}/data;DB_CLOSE_ON_EXIT=FALSE
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always